/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_move_free(a: number, b: number): void;
export function __wbg_get_move_free(a: number): number;
export function __wbg_set_move_free(a: number, b: number): void;
export function __wbg_get_move_grid(a: number): number;
export function __wbg_set_move_grid(a: number, b: number): void;
export function __wbg_get_move_pos(a: number): number;
export function __wbg_set_move_pos(a: number, b: number): void;
export function __wbg_tictacthrow_free(a: number, b: number): void;
export function __wbg_get_tictacthrow_owned(a: number): Array;
export function __wbg_set_tictacthrow_owned(a: number, b: number, c: number): void;
export function __wbg_get_tictacthrow_full(a: number): Array;
export function __wbg_set_tictacthrow_full(a: number, b: number, c: number): void;
export function __wbg_get_tictacthrow_free(a: number): number;
export function __wbg_set_tictacthrow_free(a: number, b: number): void;
export function __wbg_get_tictacthrow_contested(a: number): number;
export function __wbg_set_tictacthrow_contested(a: number, b: number): void;
export function __wbg_get_tictacthrow_grid(a: number): number;
export function __wbg_set_tictacthrow_grid(a: number, b: number): void;
export function __wbg_get_tictacthrow_player(a: number): number;
export function __wbg_set_tictacthrow_player(a: number, b: number): void;
export function __wbg_get_tictacthrow_turn(a: number): number;
export function __wbg_set_tictacthrow_turn(a: number, b: number): void;
export function __wbg_get_tictacthrow_past_state(a: number): Array;
export function __wbg_set_tictacthrow_past_state(a: number, b: number, c: number): void;
export function tictacthrow_jsonify(a: number): Array;
export function tictacthrow_get_board_by_grid(a: number, b: number): Array;
export function tictacthrow_new(): number;
export function tictacthrow_is_valid_move(a: number, b: number, c: number): number;
export function tictacthrow_get_valid_moves(a: number, b: number): Array;
export function tictacthrow_update(a: number, b: number, c: number): void;
export function tictacthrow_check_for_three(a: number, b: number): number;
export function greet(): void;
export const __wbindgen_export_0: WebAssembly.Table;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __externref_drop_slice(a: number, b: number): void;
export function __externref_table_alloc(): number;
export function __wbindgen_start(): void;
